### ISSUE TITLE
Error unmatched selector for template which only prints a variable

### ISSUE THREAD

**Issue by Erikvv** [biesbjerg/ngx-translate-extract#116]
```ts
import { Component } from '@angular/core';

@Component({
    template: '{{ variable }}'
})
export class MyComponent {
    variable: string
}
```

```
/home/erik/projects/wieluitlijning/node_modules/css-what/index.js:85
		throw new SyntaxError("Unmatched selector: " + selector);
		^

SyntaxError: Unmatched selector: {{ variable }}
    at parse (/home/erik/projects/wieluitlijning/node_modules/css-what/index.js:85:9)
    at compileUnsafe (/home/erik/projects/wieluitlijning/node_modules/cheerio/node_modules/css-select/lib/compile.js:31:14)
    at select (/home/erik/projects/wieluitlijning/node_modules/cheerio/node_modules/css-select/index.js:18:49)
    at CSSselect (/home/erik/projects/wieluitlijning/node_modules/cheerio/node_modules/css-select/index.js:41:9)
    at initialize.exports.find (/home/erik/projects/wieluitlijning/node_modules/cheerio/lib/api/traversing.js:40:21)
    at initialize.module.exports (/home/erik/projects/wieluitlijning/node_modules/cheerio/lib/cheerio.js:88:18)
    at new initialize (/home/erik/projects/wieluitlijning/node_modules/cheerio/lib/static.js:34:20)
    at initialize (/home/erik/projects/wieluitlijning/node_modules/cheerio/lib/static.js:31:14)
    at DirectiveParser._parseTemplate (/home/erik/projects/wieluitlijning/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/directive.parser.js:32:9)
    at DirectiveParser.extract (/home/erik/projects/wieluitlijning/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/directive.parser.js:26:21)
```

**Comment by biesbjerg** [comment]
Fixed in upcoming version

**Comment by YakirSmartag** [comment]
> Fixed in upcoming version

Excellent! When will it be released?
