### ISSUE TITLE
UPD: Unexpected error in typescript.js:3495 file while extract translations - on word "import"

### ISSUE THREAD

**Issue by IgorKurkov** [biesbjerg/ngx-translate-extract#121]
`npm run extract` start to work, but go down on some component. I try to comment all the template of the last component reported below, but it doesn't show any effect. Can't solve this error, can anybody help to explain what happened?
```
- src/app/manager/participant-list/participants-settings/participants-settings.component.html
- src/app/manager/participant-list/participants-uploading/participants-uploading.component.html
C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:3495
            throw e;
            ^

Error: Debug Failure.
    at parseUpdateExpression (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:19158:22)
    at parseUnaryExpressionOrHigher (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:19030:40)
    at parseBinaryExpressionOrHigher (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:18847:31)
    at parseAssignmentExpressionOrHigher (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:18513:24)
    at parseExpression (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:18443:24)
    at doOutsideOfContext (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:16688:20)
    at allowInAnd (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:16710:20)
    at parseExpressionOrLabeledStatement (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:20045:30)
    at parseStatement (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:20281:20)
    at parseListElement (C:\Projects\project\node_modules\@biesbjerg\ngx-translate-extract\node_modules\typescript\lib\typescript.js:17305:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-client@0.0.0 extract: `ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json`
npm ERR! Exit status 1
```
any ideas?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'extract' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'preextract', 'extract', 'postextract' ]
5 info lifecycle project-client@0.0.0~preextract: project-client@0.0.0
6 info lifecycle project-client@0.0.0~extract: project-client@0.0.0
7 verbose lifecycle projectclient@0.0.0~extract: unsafe-perm in lifecycle true
8 verbose lifecycle projectclient@0.0.0~extract: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Projects\project\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\igor\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\igor\AppData\Local\Microsoft\WindowsApps;C:\Users\igor\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\igor\AppData\Roaming\npm
9 verbose lifecycle project-client@0.0.0~extract: CWD: C:\Projects\project
10 silly lifecycle project-client@0.0.0~extract: Args: [ '/d /s /c',
10 silly lifecycle   'ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json' ]
11 silly lifecycle project-client@0.0.0~extract: Returned: code: 1  signal: null
12 info lifecycle project-client@0.0.0~extract: Failed to exec extract script
13 verbose stack Error: projectclient@0.0.0 extract: `ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid project-client@0.0.0
15 verbose cwd C:\Projects\project
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "extract"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error project-client@0.0.0 extract: `ngx-translate-extract --input ./src --output ./src/assets/i18n/en.json`
22 error Exit status 1
23 error Failed at the project-client@0.0.0 extract script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by IgorKurkov** [comment]
UPD: I founded the bug: the lib fails when try to extract translations from the component, where simple checkbox has in label word "import". When I changed it to "importing" or "impor" without one letter - extract works fine. 
It's a bug I think, can anyone change issue type?

**Comment by biesbjerg** [comment]
Can you please provide a component with template that fails on extract?

**Comment by IgorKurkov** [comment]
> Can you please provide a component with template that fails on extract?

not now, but I left this here as a solution, maybe some who will have a similar problem

**Comment by IgorKurkov** [comment]
hmm.... so I'm reproduce it much quicker than I expected
![image](https://user-images.githubusercontent.com/29090227/59463256-45ab3a00-8e2e-11e9-8f77-dbb9ac31fe6c.png)
```
<div class="form-row">
      <div class="input-wrapper full">
        <div class="styled-checkbox">
          <input id="delete" type="checkbox" value="1" class="styled-input-checkbox" name="isDeleteBeforeUpload" [(ngModel)]="model.isDeleteBeforeUpload" #deleteRef="ngModel" />
          <label for="delete">
            <svg width="14" height="12" viewBox="0 0 14 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.10351 8.41241L1.45582 5.76474L0 7.22056L3.49397 10.7145L3.49798 10.7105L4.13584 11.3483L14 1.48411L12.5159 9.61325e-09L4.10351 8.41241Z"/></svg>
            import
          </label>
        </div>
      </div>
    </div>
```
If I would delete word "import" with lowercase first letter - It cause error. If letter will be Capitalized - there are no error. also allowed "impor", "importlalala" etc. Only lowercased "import" cause an error which was very hard to recognize.

**Comment by biesbjerg** [comment]
Thanks, I was able to reproduce it using the current release. It's working in the next version I'm currently working on though, not sure what caused it. :)

**Comment by IgorKurkov** [comment]
Great that you were able to reproduce it! Hope this info will help you fix it fluently. Cheers :)
