### ISSUE TITLE
TypeError: Cannot read property 'typeName' of undefined

### ISSUE THREAD

**Issue by unlight** [biesbjerg/ngx-translate-extract#146]
ngx-translate-extract v1.0.0
```
TypeError: Cannot read property 'typeName' of undefined
    at c:\Dev\cloudit-frontend\node_modules\ngx-translate-extract\dist\parsers\service.parser.js:51:48
    at Array.find (<anonymous>)
    at ServiceParser._getInstancePropertyName (c:\Dev\cloudit-frontend\node_modules\ngx-translate-extract\dist\parsers\service.parser.js:47:49)
    at ServiceParser.extract (c:\Dev\cloudit-frontend\node_modules\ngx-translate-extract\dist\parsers\service.parser.js:28:43)
    at c:\Dev\cloudit-frontend\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:53:58
    at Array.forEach (<anonymous>)
    at c:\Dev\cloudit-frontend\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:52:32
    at Array.forEach (<anonymous>)
    at c:\Dev\cloudit-frontend\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:47:58
    at Array.forEach (<anonymous>)
```

String which causes issue
```
@Inject('console') private readonly console
```

```
import { ErrorHandler, Inject, Injectable } from '@angular/core';
@Injectable()
export class AppErrorHandler extends ErrorHandler {
    constructor(@Inject('console') private readonly console) {
        super();
    }
}
```

**Comment by biesbjerg** [comment]
Please update your version. Latest version is 4.2.0

**Comment by unlight** [comment]
Sorry, I installed `ngx-translate-extract` instead of `@biesbjerg/ngx-translate-extract`
