### ISSUE TITLE
Extracion fails with ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by primus852** [biesbjerg/ngx-translate-extract#210]
Hi, thank you for a this awesome tool. I am actually using it in a bigger project, but today I decided to go for a new project. Unfortunately the extractor throws an error now:

*My Extraction* 
`ngx-translate-extract --input ./src --input --output ./src/assets/i18n/de-DE.json --output ./src/app/translation/assets/en-US.json --clean --sort --format json --marker TRANSLATE`

*The Result*
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at normalize (path.js:266:5)
    at Array.map (<anonymous>)
    at processValue (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs-parser\index.js:543:43)
    at setArg (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs-parser\index.js:461:19)
    at eatArray (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs-parser\index.js:449:5)
    at parse (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs-parser\index.js:189:13)
    at Function.Parser.detailed (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs-parser\index.js:1022:10)
    at Object.parseArgs [as _parseArgs] (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs\build\lib\yargs.js:998:31)
    at Object.parse (D:\Projects\project\frontend\node_modules\@biesbjerg\ngx-translate-extract\node_modules\yargs\build\lib\yargs.js:584:29) {
  code: 'ERR_INVALID_ARG_TYPE'
```

I am using it with Angular 10, that is the only difference I can spot to my other project, is that maybe the reason?

Any hint is highly appreciated!

cheers,

PrimuS

**Comment by biesbjerg** [comment]
Are you on the latest version?

Try removing the extraneous empty `--input` argument.

From:
`ngx-translate-extract --input ./src --input --output ./src/assets/i18n/de-DE.json --output ./src/app/translation/assets/en-US.json --clean --sort --format json`

To:
`ngx-translate-extract --input ./src --output ./src/assets/i18n/de-DE.json --output ./src/app/translation/assets/en-US.json --clean --sort --format json`

*Note: `--marker` is not a valid argument in current version.*

**Comment by primus852** [comment]
> Try removing the extraneous empty `--input` argument.

That was it! Thank you!
