### ISSUE TITLE
Error generating with Angular 16

### ISSUE THREAD

**Issue by GeorgBreithaupt** [biesbjerg/ngx-translate-extract#267]
When I run it on Angular 16 with typescript 5.1.3 I get the following error:

C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\typescript\lib\typescript.js:27865
      languageVersion,
      ^

TypeError: Cannot destructure property 'languageVersion' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
    at Object.createSourceFile (C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\typescript\lib\typescript.js:27865:7)
    at ServiceParser.AbstractAstParser._createSourceFile (C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\ngx-translate-extract\dist\parsers\abstract-ast.parser.js:8:19)
    at ServiceParser.extract (C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\ngx-translate-extract\dist\parsers\service.parser.js:27:33)
    at C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:53:58
    at Array.forEach (<anonymous>)
    at C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:52:32
    at Array.forEach (<anonymous>)
    at C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:47:58
    at Array.forEach (<anonymous>)
    at ExtractTask._extract (C:\Users\Georg\source\repos\BykSupport\Byk.Support.Client\node_modules\ngx-translate-extract\dist\cli\tasks\extract.task.js:46:21)

My tsconfig.json looks like this:

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

**Comment by michaelbromley** [comment]
This repo is unmaintained. An updated fork is here: https://github.com/vendure-ecommerce/ngx-translate-extract

For background see https://github.com/biesbjerg/ngx-translate-extract/issues/246#issuecomment-1211682548
