### ISSUE TITLE
Cannot find module ../dist/cli/cli Error

### ISSUE THREAD

**Issue by burakkilic** [biesbjerg/ngx-translate-extract#86]
Hi,

I'm getting that error when I try to run the script like:

       ngx-translate-extract --input ./fdmetronic --output ./fdmetronic/i18n/*.json --clean --sort --format namespaced-json

Where am I wrong?

**Comment by ddalcero** [comment]
Same here. Did you find a solution?

**Comment by biesbjerg** [comment]
I can't reproduce. Is this still an issue?

**Comment by earyzhe** [comment]
I'm getting this issue at the moment.

My npm script is : 

`"i18n:init": "ngx-translate-extract --input ./src --output ./src/assets/i18n/template.json --key-as-default-value --replace --format json",`

    `"i18n:extract": "ngx-translate-extract --input ./src --output ./src/assets/i18n/{en,de,fr}.json --clean --format json",`


Error log: 
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '../dist/cli/cli'
Require stack:
- C:\Users\rj\Documents\Projekte\Kookie\Kookie.webui\node_modules\@biesbjerg\ngx-translate-extract\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\rj\Documents\Projekte\Kookie\Kookie.webui\node_modules\@biesbjerg\ngx-translate-extract\bin\cli.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\rj\\Documents\\Projekte\\Kookie\\Kookie.webui\\node_modules\\@biesbjerg\\ngx-translate-extract\\bin\\cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Kookie-web-ui@0.0.0 i18n:init: `ngx-translate-extract --input ./src --output ./src/assets/i18n/template.json --key-as-default-value --replace --format json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Kookie-web-ui@0.0.0 i18n:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rj\AppData\Roaming\npm-cache\_logs\2020-08-13T13_32_07_598Z-debug.log
