### ISSUE TITLE
Error extracting strings

### ISSUE THREAD

**Issue by falecomleonardolima** [biesbjerg/ngx-translate-extract#90]
Hello.
I'm testing the ngx-translate-extract tool.
When I use the "npm run extract" command, an error occurs.
..node_modules\css-what\index.js:97
                var sub = selector.match(re_name)[0];
                                                 ^

TypeError: Cannot read property '0' of null
    at getName (..node_modules\css-what\index.js:97:36)
    at parseSelector (..node_modules\css-what\index.js:184:12)
    at parse (..node_modules\css-what\index.js:82:13)
    at compileUnsafe (..node_modules\css-select\lib\compile.js:31:14)
    at select (..node_modules\css-select\index.js:18:49)
    at CSSselect (..node_modules\css-select\index.js:41:9)
    at initialize.exports.find (..node_modules\cheerio\lib\api\traversing.js:40:21)
    at initialize.module.exports (..node_modules\cheerio\lib\cheerio.js:88:18)
    at new initialize (..node_modules\cheerio\lib\static.js:34:20)
    at initialize (..node_modules\cheerio\lib\static.js:31:14)
	
..node_modules\css-what\index.js:97
                var sub = selector.match(re_name)[0];
                                                 ^

TypeError: Cannot read property '0' of null
    at getName (..node_modules\css-what\index.js:97:36)
    at parseSelector (..node_modules\css-what\index.js:184:12)
    at parse (..node_modules\css-what\index.js:82:13)
    at compileUnsafe (..node_modules\css-select\lib\compile.js:31:14)
    at select (..node_modules\css-select\index.js:18:49)
    at CSSselect (..node_modules\css-select\index.js:41:9)
    at initialize.exports.find (..node_modules\cheerio\lib\api\traversing.js:40:21)
    at initialize.module.exports (..node_modules\cheerio\lib\cheerio.js:88:18)
    at new initialize (..node_modules\cheerio\lib\static.js:34:20)
    at initialize (..node_modules\cheerio\lib\static.js:31:14)	

How can I solve this problem?

**Comment by matheo** [comment]
This cannot be the reason because the script should process the translated strings (`{{ string | translate }}`), are you sure you tracked the issue correctly? your issue seems related with `cheerio`, I don't remember how I avoided its usage but my `extract` script looks like:
```
"extract": "ngx-translate-extract --input ./src/app --output ./src/assets/i18n/*.json --clean --sort --format namespaced-json --marker _ --fi '  '"
```

**Comment by amnporter** [comment]
Any traction on this? Not sure what is causing the error?

**Comment by DenderMen** [comment]
If this is still an issue, I figured out, how to avoid this error: 
Do not use the same "extract" script for extracting strings and updating strings. I added another script for updating which has as output directory *.pot instead of template.pot.

**Comment by stomo21** [comment]
Fixed this issue on my project by going to file it errors out on and wrapping the template in any kind of html for the parser.

@Component({
    template: 'Logging out..'
})

to 

@Component({
    template: '<p>Logging out...</p>'
})

**Comment by ganqqwerty** [comment]
hmm, none of the advice helped me with the same issue

**Comment by SanyaBeer** [comment]
Same error, if add tag to template, extracting finished

**Comment by biesbjerg** [comment]
I cannot reproduce this. Can someone provide me with a minimal project that triggers the error when run through extract?

**Comment by zavakare** [comment]
I get this error and I am using version 4.2.0. Why do we get this error? I am getting it when I am doing an npm install.
