### ISSUE TITLE
Unicode support in the extract

### ISSUE THREAD

**Issue by Gidmark** [biesbjerg/ngx-translate-extract#94]
Using 2.3.4 of ngx-translate-extract. It seems like the tool is crashing whenever i add some unicode characters to the file (and convert it to a unicode file). I tried adding ✔ and everything works fine. But when i try to extract new texts it crashes on "Saving":
```
undefined:1
﻿{
^
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at NamespacedJsonCompiler.parse (D:\...Web\node_modules\@biesbjerg\ngx-translate-extract\dist\compilers\namespaced-json.compiler.js:20:40)
    at D:\....Web\node_modules\@biesbjerg\ngx-translate-extract\dist\cli\tasks\extract.task.js:71:58
    at Array.forEach (<anonymous>)
    at ExtractTask._save (D:\....Web\node_modules\@biesbjerg\ngx-translate-extract\dist\cli\tasks\extract.task.js:59:22)
    at ExtractTask.execute (D:\...Web\node_modules\@biesbjerg\ngx-translate-extract\dist\cli\tasks\extract.task.js:32:14)
    at Object.<anonymous> (D:\...Web\node_modules\@biesbjerg\ngx-translate-extract\dist\cli\cli.js:111:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by biesbjerg** [comment]
For now, please save files without BOM. Fixed in next version
